### ISSUE TITLE
How does this work? 

### ISSUE THREAD

**Issue by FaribaMp** [MajeQafouri/EasyDeadLetter#2]
Hi,
Thanks for this useful package.
I have problem with that, I want to requeue failed messages until it throw exception. How can I do this with your package?

**Comment by MattGhafouri** [comment]
I'm happy you've found the package useful.
Just follow the Readme instruction.
https://github.com/MajeQafouri/EasyDeadLetter

you can also check the article on Medium  
https://m-qafouri.medium.com/implement-dead-letter-queue-for-easynetq-rabbitmq-f0138ef23f5f

in case you had some difficulty, let me know.

**Comment by MattGhafouri** [comment]
> Hi, Thanks for this useful package. I have problem with that, I want to requeue failed messages until it throw exception. How can I do this with your package?

Actually, the mechanism which is used by this package is as follows:
1- you have subscribed to a queue
2-consumer receives the message, but in the middle of the process, something goes wrong, the message will be enqueued for the first time in the original queue,
3- for the second time RabbitMQ tries to send the already enqueued message toward the consumer, this time in case of failure the message will be sent to the dead letter queue which is already defined by the attribute.
4- if a queue does not have the attribute after a second-time failure the failed message will be written in RabbitMQ Default Error queue.
